name: pr_to_develop

on:
  pull_request:
    branches:
    - 'develop'
    
jobs:
  ci:
    uses: ./.github/workflows/reusable.terraform_ci.yml
    secrets: inherit

  tf_plan:
    needs: ci
    strategy:
      matrix:
        env: [dev,stg,prd]
    uses: ./.github/workflows/reusable.terraform_cd.yml
    secrets: inherit
    with:
      environment: ${{ matrix.env }}
      is_apply: false
      